=== andreasweberd/openyabs/MPV5/ext/mpv5.dtd
<!--Root element of any MPv5 XML file-->
<!ELEMENT mpv5 ( contacts|countries )* >
<!--END Root element of any MPv5 XML file-->


<!--CONTACTS-->
<!ELEMENT Addedby ( #PCDATA ) >
<!ELEMENT CName ( #PCDATA ) >
<!ELEMENT CNumber ( #PCDATA ) >
<!ELEMENT City ( #PCDATA ) >
<!ELEMENT Company ( #PCDATA ) >
<!ELEMENT Dateadded ( #PCDATA ) >
<!ELEMENT Fax ( #PCDATA ) >
<!--Must match a valid entry if existing-->
<!ELEMENT IDS ( #PCDATA ) >
<!-- default: 'false' -->
<!ELEMENT Iscustomer ( #PCDATA ) >
<!-- default: 'false' -->
<!ELEMENT Ismanufacturer ( #PCDATA ) >
<!-- default: 'false' -->
<!ELEMENT Issupplier ( #PCDATA ) >
<!-- default: 'false' -->
<!ELEMENT isCompany ( #PCDATA ) >
<!-- default: 'true' -->
<!ELEMENT isEnabled ( #PCDATA ) >
<!-- default: 'true' -->
<!ELEMENT isMale ( #PCDATA ) >
<!ELEMENT Mailaddress ( #PCDATA ) >
<!ELEMENT Mainphone ( #PCDATA ) >
<!ELEMENT Mobilephone ( #PCDATA ) >
<!ELEMENT Notes ( #PCDATA ) >
<!ELEMENT Prename ( #PCDATA ) >
<!ELEMENT Street ( #PCDATA ) >
<!ELEMENT Taxnumber ( #PCDATA ) >
<!ELEMENT Title ( #PCDATA ) >
<!ELEMENT Website ( #PCDATA ) >
<!ELEMENT Workphone ( #PCDATA ) >
<!ELEMENT Zip ( #PCDATA ) >
<!ELEMENT Department ( #PCDATA ) >
<!-- default: '1' -->
<!ELEMENT Groupsids ( #PCDATA ) >
<!ELEMENT contact ( CName | CNumber? | Taxnumber? | Groupsids | Title? | Prename? | Street? | Zip? | City? | Mainphone? | Workphone? | Fax? | Mobilephone? | Mailaddress? | Website? | Notes? | isMale? | isEnabled? | isCompany? | Iscustomer? | Ismanufacturer? | Issupplier? | Company? | Dateadded? | Addedby? | Department? | IDS? )* >
<!ELEMENT contacts ( contact* ) >
<!ATTLIST contact id CDATA #REQUIRED>
<!--END CONTACTS-->


<!--COUNTRIES-->
<!ELEMENT country ( #PCDATA ) >
<!ELEMENT countries ( country* ) >
<!ATTLIST country iso CDATA #REQUIRED>
<!--END COUTRIES-->

=== andreasweberd/openyabs/MPV5/contacts.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE mpv5 PUBLIC "-//http://code.google.com/p/mp-rechnungs-und-kundenverwaltung//DTD mpv5 V 1.0//EN"
"http://mp-rechnungs-und-kundenverwaltung.googlecode.com/files/mpv5.dtd">
<mpv5>
<contacts>
  <contact id="2">
    <CName>uhik</CName>
    <CNumber>tyu</CNumber>
    <Taxnumber>tyu</Taxnumber>
    <Title>tyu</Title>
    <Prename>56u</Prename>
    <Street>tyu</Street>
    <Zip>768</Zip>
    <City>uy</City>
    <Mainphone>i768768</Mainphone>
    <Workphone>76876</Workphone>
    <Fax>8768</Fax>
    <Mobilephone>867</Mobilephone>
    <Mailaddress>867876</Mailaddress>
    <Website>768yuikryui</Website>
    <Notes>uyiiiiu 5fghjkryjghui6tyhgmry7uirtyjk67i</Notes>
    <isMale>true</isMale>
    <isEnabled>true</isEnabled>
    <isCompany>false</isCompany>
    <Iscustomer>true</Iscustomer>
    <Ismanufacturer>false</Ismanufacturer>
    <Issupplier>false</Issupplier>
    <Company>3</Company>
    <Dateadded>Mon Feb 16 00:00:00 CET 2009</Dateadded>
    <Addedby>nobody</Addedby>
    <IDS>2</IDS>
  </contact>
</contacts>
</mpv5>
